version: "3.8"
services:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container2
    command: python manage.py runserver 0.0.0.0:8000